name: cruzawl
version: 1.0.9+9
description: Library for the CRUZ cryptocurrency and the cruzbit.1 network.
author: Green Appers, Inc. <greenappers@gmail.com>
homepage: https://github.com/GreenAppers/cruzawl

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  bip32: ^1.0.5
  bip39: ^1.0.3
  bs58check: ^1.0.1
  convert: ^2.1.1
  collection: ^1.14.11
  dartssh:
    git:
      url: https://github.com/GreenAppers/dartssh
  ed25519_hd_key:
    git:
      url: https://github.com/GreenAppers/dart-ed25519-hd-key
  ethereum_util:
    git:
      url: https://github.com/GreenAppers/ethereum_util
  fixnum: ^0.10.9
  http: ^0.12.0+2
  json_annotation: ^3.0.0
  merkletree: ^1.0.3
  meta: ^1.1.6
  pedantic: ^1.8.0
  pointycastle: ^1.0.2
  sembast: ^2.0.1
  tweetnacl:
    git:
      url: https://github.com/GreenAppers/tweetnacl-dart
  tweetnacl_musig:
    git:
      url: https://github.com/GreenAppers/tweetnacl-musig

dev_dependencies:
  build_runner: ^1.4.0
  json_serializable: ^3.2.0
  test: ^1.6.5
