name: cruzawl
version: 1.0.0+0
description: Library for CRUZ cryptocurrency
author: Green Appers, Inc. <greenappers@gmail.com>
homepage: https://github.com/GreenAppers/cruzawl
documentation: https://github.com/GreenAppers/cruzawl/wiki

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  ed25519_hd_key: ^1.0.1
  json_annotation: ^2.4.0
  pointycastle: ^1.0.1
  tweetnacl: ^0.3.1

dev_dependencies:
  build_runner: ^1.4.0
  json_serializable: ^3.0.0
