name: cruzawl
version: 1.0.8+8
description: Library for the CRUZ cryptocurrency and the cruzbit.1 network.
author: Green Appers, Inc. <greenappers@gmail.com>
homepage: https://github.com/GreenAppers/cruzawl

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  bip39: ^1.0.3
  convert: ^2.1.1
  collection: ^1.14.11
  ed25519_hd_key: ^1.0.1
  fixnum: ^0.10.9
  json_annotation: ^3.0.0
  meta: ^1.1.6
  pointycastle: ^1.0.1
  sembast: ^2.0.1
  tweetnacl: ^0.3.2

dev_dependencies:
  build_runner: ^1.4.0
  json_serializable: ^3.2.0
  test: ^1.6.5
